export enum Logs {
	ENDPOINT_RECEIVED_REQUEST = 'Endpoint received a request',
	INVALID_SESSION_ID = 'Error! Session Id not valid',
	INVALID_ROOM_ID = 'Error! Room Id not valid',
	INVALID_REQUEST_CONTENT = 'Error! Request content not valid',
	INVALID_BOT_USERNAME_SETTING = 'The Bot User does not exist.',
	INVALID_VISITOR_TOKEN = 'Error: Visitor Token not valid',
	INVALID_DEPARTMENT_NAME = 'Error: Department Name is not valid',
	INVALID_EVENT_DATA = 'Error! Event Data not valid',
	INVALID_MESSAGES = 'Error! Messages data not present or in wrong format. Kindly refer the api documentation.',
	ENDPOINT_REQUEST_PROCESSING_ERROR = 'Error occurred while processing the request. Details:- ',
	INVALID_ENDPOINT_ACTION = 'Error!! Invalid Action type',
	EMPTY_CLIENT_EMAIL_OR_PRIVATE_KEY_SETTING = 'Client Email or Private Key Field cannot be empty',
	EMPTY_BOT_USERNAME_SETTING = 'The Bot Username setting is not defined.',
	GOOGLE_AUTH_SUCCESS = '------------------ Google Credentials validation Success ----------------',
	DIALOGFLOW_REST_API_ERROR = 'Error occurred while using Dialogflow Rest API. Details:-',
	INVALID_RESPONSE_FROM_DIALOGFLOW = 'Error!! Invalid Response From Dialogflow',
	INVALID_RESPONSE_FROM_DIALOGFLOW_CONTENT_UNDEFINED = "Error Parsing Dialogflow's Response. Content is undefined",
	ACCESS_TOKEN_ERROR = 'Error retrieving access token',
	HTTP_REQUEST_ERROR = 'Error occurred while sending a HTTP Request',
	CLOSE_CHAT_REQUEST_FAILED_ERROR = 'Error: Internal Server Error. Could not close the chat',
	HANDOVER_REQUEST_FAILED_ERROR = 'Error occurred while processing handover. Details',
	NO_AGENTS_ONLINE = 'Handover failed! No agents online',
}
